### ISSUE TITLE
Add Test Cases

### ISSUE THREAD

**Issue by BryanL2303** [AY2324S2-CS2103T-T15-4/tp#122]
Get CodeCov to 75% or above.

**Comment by gavin331** [comment]
Also need to rename the test methods to follow the convention.

Underscores may be used in test method names using the following three part format featureUnderTest_testScenario_expectedBehavior()

e.g. sortList_emptyList_exceptionThrown() getMember_memberNotFound_nullReturned

Third part or both second and third parts can be omitted depending on what's covered in the test. For example, the test method sortList_emptyList() will test sortList() method for all variations of the 'empty list' scenario and the test method sortList() will test the sortList() method for all scenarios.
