### ISSUE TITLE
[PE-D][Tester C] Employee ID and list numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-4/tp#157]
Steps to reproduce:

1. Add a new employee
2. Delete an older employee further up in the list
3. List all the employees again

![image.png](https://raw.githubusercontent.com/tanqinyong/ped/main/files/06d9f524-d847-4769-9663-53917d61886b.png)

Expected: Remove list numbers so you can just have the IDs there and refer to IDs only.
Actual: Both list numbers and IDs are there.

Problematic behaviour: Very minor nitpicking, but i feel like it is very confusing to have the listed numbers (1 ,2 ,3 ,4 ,5 ,6) but we need to refer to the employee ID to use the commands instead. My first instinct was to enter `delete 6` to remove `ALEX YEOH` but i realised that it should be employee ID so `delete 10` instead. Users may incorrectly assume that the list numbers are the IDs and run commands on using list numbers instead. 

It would be good to remove those list numbers as it would seem that your program does not use it at all (only uses task/employee IDs). Keeping them in would just cause confusion for first time users.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tanqinyong/ped#2

**Comment by gavin331** [comment]
Similar to a previous issue, can just explain in the UG to guide the users to look at the IDs instead of the list numbers
