### ISSUE TITLE
[PE-D][Tester C] Task IDs and list number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-4/tp#160]
Steps to reproduce:

1. Add a new task
2. Delete an older task further up in the list
3. List all the tasks again

![image.png](https://raw.githubusercontent.com/tanqinyong/ped/main/files/eea2e9d7-1448-46dc-ba4d-7cf54e170a3a.png)

Expected: Remove list numbers so you can just have the IDs there and refer to IDs only.
Actual: Both list numbers and IDs are there.

Problematic behaviour:

Likewise with the tasks, it's confusing to have both the list numbers AND the task IDs displayed but only use IDs for the commands. Users may incorrectly assume that the list numbers are the IDs and run commands on using list numbers instead. It is confusing to have the listed numbers (1 ,2 ,3 ,4 ) but we need to refer to the task ID to use the commands instead.

It would be good to remove those list numbers as it would seem that your program does not use it at all (only uses task/employee IDs). Keep them in would just cause confusion for first time users.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tanqinyong/ped#3

**Comment by gavin331** [comment]
Can explain better in the UG to mitigate this.
