### ISSUE TITLE
[PE-D][Tester D] Same error message used for different types of errors for unassigntask command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-4/tp#179]
Steps to reproduce:
1. Ensure tasks with task ID 1 and 2 exist, and ensure employees with id 4 and 5 exist.
2. Type `unassigntask 1 5`
![image.png](https://raw.githubusercontent.com/yuhinarita/ped/main/files/a8c4a8be-785f-49f2-baa7-5d3854e1208e.png)

3. Type `unassigntask -1 5`
![image.png](https://raw.githubusercontent.com/yuhinarita/ped/main/files/72712c14-ce02-4415-adfa-f72cb33b398e.png)

Expected Behaviour: Error message at step 2 should say something like `this task has not yet been assigned`

Actual: 
Error messages for a genuinely invalid ID e.g. -1 in step 3, and a not found error (as in step 2) is the same.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: yuhinarita/ped#11

**Comment by BryanL2303** [comment]
Same as #184
